//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DoenaSoft.DVDProfiler.EnhancedNotes.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Texts {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Texts() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("DoenaSoft.DVDProfiler.EnhancedNotes.Resources.Texts", typeof(Texts).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to About.
        /// </summary>
        internal static string About {
            get {
                return ResourceManager.GetString("About", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancel.
        /// </summary>
        internal static string Cancel {
            get {
                return ResourceManager.GetString("Cancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Check for Updates.
        /// </summary>
        internal static string CheckForUpdates {
            get {
                return ResourceManager.GetString("CheckForUpdates", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Copy all data to clipboard.
        /// </summary>
        internal static string CopyAllToClipboard {
            get {
                return ResourceManager.GetString("CopyAllToClipboard", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Copy note to clipboard.
        /// </summary>
        internal static string CopyCurrentToClipboard {
            get {
                return ResourceManager.GetString("CopyCurrentToClipboard", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit.
        /// </summary>
        internal static string Edit {
            get {
                return ResourceManager.GetString("Edit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enhanced Notes.
        /// </summary>
        internal static string EN {
            get {
                return ResourceManager.GetString("EN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Export Options.
        /// </summary>
        internal static string ExportOptions {
            get {
                return ResourceManager.GetString("ExportOptions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Export to Collection.xml.
        /// </summary>
        internal static string ExportToCollectionXml {
            get {
                return ResourceManager.GetString("ExportToCollectionXml", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Export to XML.
        /// </summary>
        internal static string ExportToXml {
            get {
                return ResourceManager.GetString("ExportToXml", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Help.
        /// </summary>
        internal static string Help {
            get {
                return ResourceManager.GetString("Help", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Import from XML.
        /// </summary>
        internal static string ImportFromXml {
            get {
                return ResourceManager.GetString("ImportFromXml", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Import Options.
        /// </summary>
        internal static string ImportOptions {
            get {
                return ResourceManager.GetString("ImportOptions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invelos Data.
        /// </summary>
        internal static string InvelosData {
            get {
                return ResourceManager.GetString("InvelosData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Is HTML.
        /// </summary>
        internal static string IsHtml {
            get {
                return ResourceManager.GetString("IsHtml", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Labels.
        /// </summary>
        internal static string Labels {
            get {
                return ResourceManager.GetString("Labels", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Load Enhanced Notes from XML.
        /// </summary>
        internal static string LoadXmlFile {
            get {
                return ResourceManager.GetString("LoadXmlFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Misc..
        /// </summary>
        internal static string Misc {
            get {
                return ResourceManager.GetString("Misc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Note 1.
        /// </summary>
        internal static string Note1 {
            get {
                return ResourceManager.GetString("Note1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Note 2.
        /// </summary>
        internal static string Note2 {
            get {
                return ResourceManager.GetString("Note2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Note 3.
        /// </summary>
        internal static string Note3 {
            get {
                return ResourceManager.GetString("Note3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Note 4.
        /// </summary>
        internal static string Note4 {
            get {
                return ResourceManager.GetString("Note4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Note 5.
        /// </summary>
        internal static string Note5 {
            get {
                return ResourceManager.GetString("Note5", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Options.
        /// </summary>
        internal static string Options {
            get {
                return ResourceManager.GetString("Options", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Paste all data from clipboard.
        /// </summary>
        internal static string PasteAllFromClipboard {
            get {
                return ResourceManager.GetString("PasteAllFromClipboard", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Paste note from clipboard.
        /// </summary>
        internal static string PasteCurrentFromClipboard {
            get {
                return ResourceManager.GetString("PasteCurrentFromClipboard", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Plugin Data.
        /// </summary>
        internal static string PluginData {
            get {
                return ResourceManager.GetString("PluginData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Allows to add more detailed notes..
        /// </summary>
        internal static string PluginDescription {
            get {
                return ResourceManager.GetString("PluginDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enhanced Notes.
        /// </summary>
        internal static string PluginName {
            get {
                return ResourceManager.GetString("PluginName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to http://doena-journal.net/en/dvd-profiler-tools/.
        /// </summary>
        internal static string PluginUrl {
            get {
                return ResourceManager.GetString("PluginUrl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Preview.
        /// </summary>
        internal static string Preview {
            get {
                return ResourceManager.GetString("Preview", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Resets the label text to its default..
        /// </summary>
        internal static string Reset {
            get {
                return ResourceManager.GetString("Reset", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to R.
        /// </summary>
        internal static string ResetLabel {
            get {
                return ResourceManager.GetString("ResetLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save.
        /// </summary>
        internal static string Save {
            get {
                return ResourceManager.GetString("Save", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save Enhanced Notes to XML.
        /// </summary>
        internal static string SaveXmlFile {
            get {
                return ResourceManager.GetString("SaveXmlFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Standard Note.
        /// </summary>
        internal static string StandardNote {
            get {
                return ResourceManager.GetString("StandardNote", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tools.
        /// </summary>
        internal static string Tools {
            get {
                return ResourceManager.GetString("Tools", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to UI Language.
        /// </summary>
        internal static string UiLanguage {
            get {
                return ResourceManager.GetString("UiLanguage", resourceCulture);
            }
        }
    }
}
